spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/emr_financas}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=${DB_SSL_MODE:disable}

spring.jpa.show-sql=true

app.dev.seed-user.enabled=${DEV_SEED_USER_ENABLED:false}
