-- Script Oracle para criacao manual das tabelas do projeto EMR Financas.
-- Caso o ddl-auto=update esteja ativo, o Spring tambem pode criar/atualizar as tabelas automaticamente.

CREATE SEQUENCE SEQ_EMR_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMR_GASTO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMR_RECEBIMENTO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMR_INVESTIMENTO START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE TB_EMR_USUARIO (
    CD_USUARIO NUMBER(19,0) PRIMARY KEY,
    NM_USUARIO VARCHAR2(100) NOT NULL,
    DS_EMAIL VARCHAR2(120) NOT NULL UNIQUE,
    DS_SENHA VARCHAR2(100) NOT NULL
);

CREATE TABLE TB_EMR_GASTO (
    CD_GASTO NUMBER(19,0) PRIMARY KEY,
    DS_DESCRICAO VARCHAR2(120) NOT NULL,
    DS_CATEGORIA VARCHAR2(80) NOT NULL,
    VL_GASTO NUMBER(12,2) NOT NULL,
    DT_GASTO DATE NOT NULL,
    DS_FORMA_PAGAMENTO VARCHAR2(60),
    DS_OBSERVACAO VARCHAR2(255),
    CD_USUARIO NUMBER(19,0),
    CONSTRAINT FK_EMR_GASTO_USUARIO FOREIGN KEY (CD_USUARIO) REFERENCES TB_EMR_USUARIO(CD_USUARIO)
);

CREATE TABLE TB_EMR_RECEBIMENTO (
    CD_RECEBIMENTO NUMBER(19,0) PRIMARY KEY,
    DS_DESCRICAO VARCHAR2(120) NOT NULL,
    DS_ORIGEM VARCHAR2(80) NOT NULL,
    VL_RECEBIMENTO NUMBER(12,2) NOT NULL,
    DT_RECEBIMENTO DATE NOT NULL,
    DS_STATUS VARCHAR2(40) NOT NULL,
    CD_USUARIO NUMBER(19,0),
    CONSTRAINT FK_EMR_RECEB_USUARIO FOREIGN KEY (CD_USUARIO) REFERENCES TB_EMR_USUARIO(CD_USUARIO)
);

CREATE TABLE TB_EMR_INVESTIMENTO (
    CD_INVESTIMENTO NUMBER(19,0) PRIMARY KEY,
    NM_INVESTIMENTO VARCHAR2(120) NOT NULL,
    DS_TIPO VARCHAR2(80) NOT NULL,
    DS_INSTITUICAO VARCHAR2(100),
    VL_APLICADO NUMBER(12,2) NOT NULL,
    NR_RENTABILIDADE NUMBER(8,2),
    DT_APLICACAO DATE NOT NULL,
    CD_USUARIO NUMBER(19,0),
    CONSTRAINT FK_EMR_INV_USUARIO FOREIGN KEY (CD_USUARIO) REFERENCES TB_EMR_USUARIO(CD_USUARIO)
);

INSERT INTO TB_EMR_USUARIO (CD_USUARIO, NM_USUARIO, DS_EMAIL, DS_SENHA)
VALUES (SEQ_EMR_USUARIO.NEXTVAL, 'Administrador EMR', 'admin@emrfinancas.com', '123456');

COMMIT;
